// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx7voEih93cWiXJYrBILCVTo6tUWutnYc',
    appId: '1:216744065614:android:6692500d0ddf83b32fa11f',
    messagingSenderId: '216744065614',
    projectId: 'clinic-44fbf',
    storageBucket: 'clinic-44fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7rqW89mS4fuQwqX9jrjiMX35L0ttuqk',
    appId: '1:216744065614:ios:c1af1c7536d45f9a2fa11f',
    messagingSenderId: '216744065614',
    projectId: 'clinic-44fbf',
    storageBucket: 'clinic-44fbf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI7rqW89mS4fuQwqX9jrjiMX35L0ttuqk',
    appId: '1:216744065614:ios:c1af1c7536d45f9a2fa11f',
    messagingSenderId: '216744065614',
    projectId: 'clinic-44fbf',
    storageBucket: 'clinic-44fbf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
